### ISSUE TITLE
harmonize "Code for" and "Code from"

### ISSUE THREAD

**Issue by Mo-Gul** [bkamins/JuliaForDataAnalysis#3]
There are 175 occurrences of "Code for" e.g.

https://github.com/bkamins/JuliaForDataAnalysis/blob/7e9aea96912798be222f2078e4b82fb137b3ac51/ch02.jl#L5

and 20 occurrences of "Code from" e.g.

https://github.com/bkamins/JuliaForDataAnalysis/blob/7e9aea96912798be222f2078e4b82fb137b3ac51/ch01.jl#L5

Is that intended? Shall I provide a PR or do you fix it yourself if this is not intended?

**Comment by bkamins** [comment]
I wanted to use "code from" for sections and "code for" for other types of references. Given your suggestion I have synchronized everything as "code for". Thank you!
