### ISSUE TITLE
make code from non-"julia modes" comments

### ISSUE THREAD

**Issue by Mo-Gul** [bkamins/JuliaForDataAnalysis#4]
I think I would make stuff that is not in "julia" mode comments. This avoids that this stuff is shown as "Parsing error" in VS Code (and most likely other IDEs). For example

https://github.com/bkamins/JuliaForDataAnalysis/blob/7e9aea96912798be222f2078e4b82fb137b3ac51/ch02.jl#L52-L53

could be changed to

```jl
# In REPL
# - change to "help mode" by pressing `?` key
# - type `₁` (or copy/paste it there)
# - type `ε` (or copy/paste it there)
# - return to "julia mode" by pressing `backspace` key
```

What do you think about that?

**Comment by bkamins** [comment]
The point was that if in Visual Studio Code you copy-paste `?₁` it automatically switches to help mode.

But following your suggestion I have changed this.

One small comment. Help mode (as opposed to package manager mode) is not sticky. Julia switches back to normal mode after displaying help.

Thank you!

**Comment by Mo-Gul** [comment]
> The point was that if in Visual Studio Code you copy-paste `?₁` it automatically switches to help mode.

Aaah, good idea. Than this would have been a good alternative to write simply this: "Please copy-paste `?₁` to the REPL."

> One small comment. Help mode (as opposed to package manager mode) is not sticky. Julia switches back to normal mode after displaying help.

True.
